### ISSUE TITLE
how do I compile wurst on linux?

### ISSUE THREAD

**Issue by x13machine** [Wurst-Imperium/Wurst-MC-1.10#51]
I downloaded the source and ran mcp. I'm confused as to what to do next.

**Comment by CisBetter** [comment]
Could you tell us which Linux distribution you are using (e.g. Debian (or Ubuntu), OpenSUSE, ArchLinux...)?

**Comment by x13machine** [comment]
ubuntu 16.04

**Comment by x13machine** [comment]
I get these errors. http://hastebin.com/uyuhenaveq.sql

**Comment by CisBetter** [comment]
It seams that you didn't apply the patch properly. Could you retry setting up everything and post the output of: `$ decompile.sh` (in MCP); `$ ./YourPatchInitialiseScript.sh 2 >&1 > /dev/null`

Also, did you install Wine / Astyle before running decompile.sh?

PS:
I think even though `Alexander01998` closed this we can fix this problem for you :smile: This issue was closed because Wurst wasn't meant to be compiled on Linux (as explained [here](https://www.wurst-client.tk/wiki/Contributing/part1/)).
> In terms of software, you should be using Eclipse LUNA as your IDE and Windows 10 as your operating system. If you use a different software or a different operating system, you will likely need to do some things differently and you might run into issues that this tutorial can’t help you with.

**Comment by x13machine** [comment]
what's the Patch Initialise Script suppose to do? Also, am I supposed to copy the contents of mcp/src/minecraft into wurst/mc?

**Comment by CisBetter** [comment]
As Minecraft is not open source nor free nobody is allowed to publish it's source code. Therefore Wurst uses patches (created with [git](https://git-scm.com/)). In order to compile Wurst you first have to apply Wurst's changes on the Minecraft source code.

1. Copy Minecraft's source code (everything in `ncp/src/minecraft/`; **NOT `ncp/src/minecraft` itself**) into `YourWurstCloneDir/mc/`
2. Apply the patch located in `YourWurstCloneDir/patch` (e.g. by using my script :arrow_double_up: )
3. Copy Minecraft's libraries (every `.jar` file in `ncp/jars/libraries/`) into `YourWurstCloneDir/lib`
4. Copy `/ncp/jars/versions` into `YourWurstCloneDir/game-output/`
3. Import the project into Eclipse (I would recommend [Eclipse NEON](https://eclipse.org/) (currently the latest release)) File > Import > General > Existing Projects into Workspace
4. Click ![the launch button](https://cloud.githubusercontent.com/assets/17952058/20146149/0d572f08-a6a3-11e6-90dd-f98a8bd31f2d.png)
4. If you still see any errors please post them below (if necessary with a screenshot)
